# -*- coding: utf-8 -*-
"""fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pf6BtKaCQZaVvz26pLOg25AKwLqODDob
"""

a, b, c = 0, 1, 2
fibonacci=[]
while c < 55:
    c = a + b
    a = b
    b = c
    fibonacci.append(c)
print("fibonacci sayıları :", fibonacci)















